/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.herumi.mcl;

public interface MclConstants {
    public static final int BN254 = 0;
    public static final int BLS12_381 = 5;
    public static final int SECP256K1 = 102;
}
