name: Publish package to the Maven Central Repository
on:
    release:
        types: [created]
    push:
        branches:
            - "master"
            - "develop"

jobs:
    if: "contains(github.event.head_commit.message, 'release:')"
    publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v2

            - name: Set up Java
              uses: actions/setup-java@v2
              with:
                  java-version: '8'
                  distribution: 'adopt'

            - name: Publish to the Maven Central Repository
              run: gradle publish
              env:
                  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
                  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSWORD }}
                  MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
