name: Test

on:
    push:
        branches:
            - "master"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Merge Conflict finder
              uses: olivernybroe/action-conflict-finder@v1.1

            - name: Use Java Version 22
              uses: actions/setup-java@v2
              with:
                  distribution: "adopt"
                  java-version: "22"
                  cache: "gradle"

            - name: Format code
              run: gradle format

            - name: Commit fixed code
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "style: resolve style guide violations"
                  branch: ${{ github.head_ref }}

    unit:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [22]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Merge Conflict finder
              uses: olivernybroe/action-conflict-finder@v1.1

            - name: Install Nix
              uses: cachix/install-nix-action@v27

            - name: Install libsecp256k1
              run: |
                nix profile install nixpkgs#secp256k1
              env:
                NIX_PATH: $HOME/.nix-profile/bin

            - name: Set LD_LIBRARY_PATH
              run: echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.nix-profile/lib" >> $GITHUB_ENV

            - name: Use Java Version ${{ matrix.java }}
              uses: actions/setup-java@v2
              with:
                  distribution: "adopt"
                  java-version: ${{ matrix.java }}
                  cache: "gradle"

            - name: Download and compile secp256k1-jdk
              run: |
                git clone https://gitlab.com/bitcoinj/secp256k1-jdk.git
                cd secp256k1-jdk
                ./gradlew build -x test
                cp secp256k1-api/build/libs/secp256k1-api-0.0.1.jar ../lib
                cp secp256k1-foreign/build/libs/secp256k1-foreign-0.0.1.jar ../lib
                rm -rf secp256k1-jdk

            - name: Install
              run: gradle dependencies

            - name: Test
              run: gradle test && gradle jacocoTestReport

            - name: Codecov
              run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
